global using MediatR;
global using ServiceModel = api.Models.Service;
global using RestaurantModel = api.Models.Restaurant;
global using ActivityModel = api.Models.Activity;
global using CityModel = api.Models.City;
global using ProvinceModel = api.Models.Province;
global using FoodTypeModel = api.Models.FoodType;
global using ReviewModel = api.Models.Review;
global using CookTypeModel = api.Models.CookType;
global using IngredientModel = api.Models.Ingredient;
global using PlateModel = api.Models.Plate;
global using CouponModel = api.Models.Coupon;
global using RestaurantReviewModel = api.Models.RestaurantReview;
global using PlateReviewModel = api.Models.PlateReview;
global using CoordinatesModel = SaborCubano.Domain.Models.Coordinates;