// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaborCubano.Infrastructure.Persistence;

#nullable disable

namespace SaborCubano.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241225222604_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.AppUserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_Activity")
                        .HasColumnType("integer");

                    b.Property<string>("Id_User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_Activity");

                    b.HasIndex("Id_User");

                    b.ToTable("AppUserActivity");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.CouponAppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Id_AppUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Coupon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_AppUser");

                    b.HasIndex("Id_Coupon");

                    b.ToTable("CouponAppUser");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.PlateCookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_CT")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Plate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_CT");

                    b.HasIndex("Id_Plate");

                    b.ToTable("PlateCookType");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.PlateIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_Ingredient")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Plate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Ingredient");

                    b.HasIndex("Id_Plate");

                    b.ToTable("PlateIngredient");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.RestaurantBussinesType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_BS")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Res")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_BS");

                    b.HasIndex("Id_Res");

                    b.ToTable("RestaurantBussinesType");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.RestaurantFoodTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_FoodTypes")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Res")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_FoodTypes");

                    b.HasIndex("Id_Res");

                    b.ToTable("RestaurantFoodTypes");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.RestaurantService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_Res")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Service")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Res");

                    b.HasIndex("Id_Service");

                    b.ToTable("RestaurantService");
                });

            modelBuilder.Entity("api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("api.Models.BussinesType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BussinesType");
                });

            modelBuilder.Entity("api.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_Prov")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_Prov");

                    b.ToTable("City");
                });

            modelBuilder.Entity("api.Models.CookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CookType");
                });

            modelBuilder.Entity("api.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Expire_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Res")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Res");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("api.Models.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodType");
                });

            modelBuilder.Entity("api.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("api.Models.Plate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<int?>("CookTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Res")
                        .HasColumnType("integer");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CookTypeId");

                    b.HasIndex("Id_Res");

                    b.HasIndex("IngredientId");

                    b.ToTable("Plate");
                });

            modelBuilder.Entity("api.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Close_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cont_Num")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email_Res")
                        .HasColumnType("text");

                    b.Property<bool?>("Have_Home")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_City")
                        .HasColumnType("integer");

                    b.Property<string>("Id_User")
                        .HasColumnType("text");

                    b.Property<bool?>("Is_Reservas")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("Open_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id_City");

                    b.HasIndex("Id_User");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DateWriting")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Id_User")
                        .HasColumnType("text");

                    b.Property<bool>("Is_Funny")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_Util")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Opinion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.PrimitiveCollection<byte[][]>("Photos")
                        .HasColumnType("bytea[]");

                    b.Property<string>("Review_Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Id_User");

                    b.ToTable("Review");

                    b.HasDiscriminator<string>("Review_Type").HasValue("Review");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("api.Models.PlateReview", b =>
                {
                    b.HasBaseType("api.Models.Review");

                    b.Property<bool>("Eat_In_Local")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_Plate")
                        .HasColumnType("integer");

                    b.Property<int>("Valoration_Plate")
                        .HasColumnType("integer");

                    b.HasIndex("Id_Plate");

                    b.ToTable("Review");

                    b.HasDiscriminator().HasValue("Plate");
                });

            modelBuilder.Entity("api.Models.RestaurantReview", b =>
                {
                    b.HasBaseType("api.Models.Review");

                    b.Property<int>("Id_Res")
                        .HasColumnType("integer");

                    b.Property<int>("Valoration_Higiene")
                        .HasColumnType("integer");

                    b.Property<int>("Valoration_Local")
                        .HasColumnType("integer");

                    b.Property<int>("Valoration_Price")
                        .HasColumnType("integer");

                    b.Property<int>("Valoration_Service")
                        .HasColumnType("integer");

                    b.HasIndex("Id_Res");

                    b.ToTable("Review");

                    b.HasDiscriminator().HasValue("Restaurant");
                });

            modelBuilder.Entity("api.Models.Administrator", b =>
                {
                    b.HasBaseType("api.Models.User");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.HasBaseType("api.Models.User");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<byte[][]>("Gallery")
                        .HasColumnType("bytea[]");

                    b.Property<int>("Id_City")
                        .HasColumnType("integer");

                    b.HasIndex("AppUserId");

                    b.HasIndex("Id_City");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("api.Models.RestaurantChief", b =>
                {
                    b.HasBaseType("api.Models.User");

                    b.ToTable("RestaurantChief", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.AppUserActivity", b =>
                {
                    b.HasOne("api.Models.Activity", "Activity")
                        .WithMany("AppUser")
                        .HasForeignKey("Id_Activity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.AppUser", "AppUser")
                        .WithMany("Activities")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.CouponAppUser", b =>
                {
                    b.HasOne("api.Models.AppUser", "AppUser")
                        .WithMany("Coupon")
                        .HasForeignKey("Id_AppUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Coupon", "Coupon")
                        .WithMany("AppUsers")
                        .HasForeignKey("Id_Coupon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.PlateCookType", b =>
                {
                    b.HasOne("api.Models.CookType", "CookType")
                        .WithMany()
                        .HasForeignKey("Id_CT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Plate", "Plate")
                        .WithMany("CookTypes")
                        .HasForeignKey("Id_Plate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookType");

                    b.Navigation("Plate");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.PlateIngredient", b =>
                {
                    b.HasOne("api.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("Id_Ingredient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Plate", "Plate")
                        .WithMany("Ingredients")
                        .HasForeignKey("Id_Plate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Plate");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.RestaurantBussinesType", b =>
                {
                    b.HasOne("api.Models.BussinesType", "BussinesType")
                        .WithMany("RestaurantBussinesTypes")
                        .HasForeignKey("Id_BS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Restaurant", "Restaurant")
                        .WithMany("BussinesTypes")
                        .HasForeignKey("Id_Res")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BussinesType");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.RestaurantFoodTypes", b =>
                {
                    b.HasOne("api.Models.FoodType", "FoodType")
                        .WithMany("Restaurants")
                        .HasForeignKey("Id_FoodTypes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Restaurant", "Restaurant")
                        .WithMany("FoodTypes")
                        .HasForeignKey("Id_Res")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodType");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SaborCubano.Domain.Models.RestaurantService", b =>
                {
                    b.HasOne("api.Models.Restaurant", "Restaurant")
                        .WithMany("Services")
                        .HasForeignKey("Id_Res")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Service", "Service")
                        .WithMany("Restaurants")
                        .HasForeignKey("Id_Service")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("api.Models.City", b =>
                {
                    b.HasOne("api.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("Id_Prov")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("api.Models.Coupon", b =>
                {
                    b.HasOne("api.Models.Restaurant", "Restaurant")
                        .WithMany("Coupons")
                        .HasForeignKey("Id_Res")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("api.Models.Plate", b =>
                {
                    b.HasOne("api.Models.CookType", null)
                        .WithMany("Plates")
                        .HasForeignKey("CookTypeId");

                    b.HasOne("api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("Id_Res")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Ingredient", null)
                        .WithMany("Plates")
                        .HasForeignKey("IngredientId");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("api.Models.Restaurant", b =>
                {
                    b.HasOne("api.Models.City", "City")
                        .WithMany("Restaurants")
                        .HasForeignKey("Id_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.RestaurantChief", "Chief")
                        .WithMany("Restaurants")
                        .HasForeignKey("Id_User");

                    b.Navigation("Chief");

                    b.Navigation("City");
                });

            modelBuilder.Entity("api.Models.Review", b =>
                {
                    b.HasOne("api.Models.AppUser", "AppUser")
                        .WithMany("Reviews")
                        .HasForeignKey("Id_User");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("api.Models.PlateReview", b =>
                {
                    b.HasOne("api.Models.Plate", "Plate")
                        .WithMany()
                        .HasForeignKey("Id_Plate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plate");
                });

            modelBuilder.Entity("api.Models.RestaurantReview", b =>
                {
                    b.HasOne("api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("Id_Res")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("api.Models.Administrator", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithOne()
                        .HasForeignKey("api.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.HasOne("api.Models.AppUser", null)
                        .WithMany("AppUsers")
                        .HasForeignKey("AppUserId");

                    b.HasOne("api.Models.User", null)
                        .WithOne()
                        .HasForeignKey("api.Models.AppUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("Id_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("api.Models.RestaurantChief", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithOne()
                        .HasForeignKey("api.Models.RestaurantChief", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Activity", b =>
                {
                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("api.Models.BussinesType", b =>
                {
                    b.Navigation("RestaurantBussinesTypes");
                });

            modelBuilder.Entity("api.Models.City", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("api.Models.CookType", b =>
                {
                    b.Navigation("Plates");
                });

            modelBuilder.Entity("api.Models.Coupon", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("api.Models.FoodType", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("api.Models.Ingredient", b =>
                {
                    b.Navigation("Plates");
                });

            modelBuilder.Entity("api.Models.Plate", b =>
                {
                    b.Navigation("CookTypes");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("api.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("api.Models.Restaurant", b =>
                {
                    b.Navigation("BussinesTypes");

                    b.Navigation("Coupons");

                    b.Navigation("FoodTypes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("api.Models.Service", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AppUsers");

                    b.Navigation("Coupon");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("api.Models.RestaurantChief", b =>
                {
                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
